### PR TITLE
iOS: Fix first screen is recomposed twice

### LINKED ISSUE #3778: First screen is recomposed twice on iOS
The following code snippet:

```
@Composable
fun App() {
    val value = remember(LocalDensity.current) {
        (1..100).random()
    }
    println("Density: ${LocalDensity.current}")
    println("value is $value")
}
```

results in the following output:

```
Density: DensityImpl(density=1.0, fontScale=1.0)
value is 15
Density: DensityImpl(density=3.0, fontScale=1.0)
value is 34
```

on iOS.

That may have side effects like in the #3766 issue.

We should initialize density to correct value  before first composition to eliminate this.

### PR DESCRIPTION
**Pull request by eymar**
Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3778

Implemented according to what @elijah-semyonov suggested:

> We need to defer the first recomposition until `didMoveToWindow` was called with non-nil window. That's when a correct density scale is available.

### CODE REVIEW

File: compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+package bugs
+
+import androidx.compose.material.Text
+import androidx.compose.mpp.demo.Screen
+import androidx.compose.runtime.remember
+import androidx.compose.ui.platform.LocalDensity
+
+// https://github.com/JetBrains/compose-multiplatform/issues/3778
+val StartRecompositionCheck = Screen.Example("Start Recomposition Check") {
+    Text("See logs. Density should be printed only once")
```
Comment (MatkovIvan) [inline compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt]: Let's just add global var and `Text("Repompositions: $count")`

File: compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt [hunk 2]
```diff
@@ -665,31 +665,35 @@ internal actual class ComposeWindow : UIViewController {
...
+                        LocalUIViewController provides this,
+                        LocalKeyboardOverlapHeightState provides keyboardOverlapHeightState,
+                        LocalSafeArea provides safeAreaState,
+                        LocalLayoutMargins provides layoutMarginsState,
+                        LocalInterfaceOrientationState provides interfaceOrientationState,
+                        LocalSystemTheme provides systemTheme.value,
+                        LocalUIKitInteropContext provides interopContext,
+                    ) {
+                        content()
+                    }
```
Comment (MatkovIvan) [inline compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt]:
```suggestion
                        content = content
                    )
```

Comment (eymar) [reply compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt]: Could you please comment your idea? Why asign it to itself? 
did you mean something else?

Comment (eymar) [reply compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt]: I see, it's an argument. not an assignment

File: compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt (hunk 1 above)
Comment (eymar) [reply compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt]: done

File: compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt (hunk 2 above)
Comment (eymar) [reply compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt]: done

File: compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+import androidx.compose.runtime.remember
+import androidx.compose.ui.platform.LocalDensity
+
+private var counter = 0
+
+// https://github.com/JetBrains/compose-multiplatform/issues/3778
+val StartRecompositionCheck = Screen.Example("Start Recomposition Check") {
+    remember {
+        counter = 0
+    }
```
Comment (MatkovIvan) [inline compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt]: I guess it won't show a repro for fixed case. it calls `remember`'s lambda twice and assign zero to it. I guess this block can be removed

Comment (eymar) [reply compose/mpp/demo/src/uikitMain/kotlin/bugs/RedundantRecompositionOnStart.kt]: Actually, this demo doesn't reproduce the issue at all, because we can only start it manually by navigating in the demos menu. By the moment it starts, the LocalDensity is already properly set and no extra recomposition occurr in this demo. 

I initially tested it on a top level and then moved the demo in iOS bugs category. We need something else to test this.

**Review by dima-avdeev-jb — APPROVED** [review]

**Review by elijah-semyonov — APPROVED** [review]
