### PR TITLE
Fix ComposeAccessibleComponent.getAccessibleChild

### LINKED ISSUE #4778: Accessibility. Crash on Windows when traversing elements
Compose 1.6.10-rc01, Windows 11, NVDA 2023.2

1. run run1
2. traverse with hot keys
3. see crash:
```
Caused by: java.lang.IndexOutOfBoundsException: index: -3, size: 1
	at kotlin.collections.AbstractList$Companion.checkElementIndex$kotlin_stdlib(AbstractList.kt:108)
	at kotlin.collections.builders.ListBuilder.get(ListBuilder.kt:59)
	at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getAccessibleChild(ComposeAccessible.kt:337)
	at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getAccessibleAt(ComposeAccessible.kt:380)
	at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getAccessibleAt(ComposeAccessible.kt:381)
	at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getAccessibleAt(ComposeAccessible.kt:381)
	at androidx.compose.ui.platform.a11y.ComposeSceneAccessible$ComposeSceneAccessibleContext.getAccessibleAt(ComposeSceneAccessible.kt:89)
	at jdk.accessibility/com.sun.java.accessibility.util.EventQueueMonitor.getAccessibleAt(EventQueueMonitor.java:441)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$12.call(AccessBridge.java:581)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$12.call(AccessBridge.java:578)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils$CallableWrapper.run(AccessBridge.java:7334)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
```

### PR DESCRIPTION
**Pull request by m-sasha**
`ComposeAccessibleComponent.getAccessibleChild` was trying to incorrectly access `auxiliaryChildren` if `controller.accessibleByNodeId` returned `null`.

Fixes https://github.com/JetBrains/compose-multiplatform/issues/4778

## Testing
1. Run the code below
2. Turn on VoiceOver
3. Scroll the list with the mouse wheel.
4. Press tab.
```
fun main() {
    application {
        Window(
            onCloseRequest = ::exitApplication
        ) {
            LazyColumn {
                items(100) {
                    Text("Item $it")
                }
            }
        }
    }
}
```
Note that this doesn't reproduce in latest jb-main, probably due to focus traversal changes.

### CODE REVIEW

File: compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/a11y/ComposeAccessible.kt [hunk 1]
```diff
@@ -332,9 +332,13 @@ internal class ComposeAccessible(
         }
 
         override fun getAccessibleChild(i: Int): Accessible? {
-            return semanticsNode.replacedChildren.getOrNull(i)?.id?.let { id ->
-                controller.accessibleByNodeId(id)
-            } ?: auxiliaryChildren[i - semanticsNode.replacedChildren.size]
+            val replacedChildren = semanticsNode.replacedChildren
+            val replacedChildrenSize = replacedChildren.size
+            return if (i < replacedChildrenSize) {
+                controller.accessibleByNodeId(replacedChildren[i].id)
```
Comment (MatkovIvan) [inline compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/a11y/ComposeAccessible.kt:338]: The only difference I see is using `get` instead of `getOrNull`. I don't really get why it should make a difference.

**Review by MatkovIvan — COMMENTED** [review]
I'd love to see unit tests for this case to prevent regressions

File: compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/a11y/ComposeAccessible.kt (hunk 1 above)
Comment (m-sasha) [reply compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/a11y/ComposeAccessible.kt:338]: controller.accessibleByNodeId can return null, in which case the old code would try to access auxiliaryChildren

**Comment by m-sasha** [comment]
> I'd love to see unit tests for this case to prevent regressions

It's a silly mistake that's not likely to be repeated, and it's hard to set up a test for this. I don't think it's worth it.

**Review by MatkovIvan — APPROVED** [review]
