### PR TITLE
Fix crash on loading UITextLoupeSession on old iOS versions

### LINKED ISSUE #4644: Android Navigation crashes on startup with SIGKILL
**Describe the bug**
Adding jetbrains compose plugin crashes on iOS devices below iOS 17
`org.jetbrains.compose:1.6.10-dev1580`

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): iOS 15.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): IPad Pro

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Download a Compose Multiplatform Wizard template
2. Add this version of the jetbrains compose plugin `1.6.10-dev1580`
3. Sync
4. Run on affected device

**Expected behavior**
Not crashing. Display the compose multiplatform template

**Additional context**
This is the stacktrace in XCode 
```
dyld[558]: Symbol not found: _OBJC_CLASS_$_UITextLoupeSession
 Referenced from: /private/var/containers/Bundle/Application/<UUID>/App.app/App
 Expected in: /System/Library/Frameworks/UIKit.framework/UIKit
```
It works using this version `2.6.2`

### PR DESCRIPTION
**Pull request by ASalavei**
## Proposed Changes
Create wrapper around UITextLoupeSession class to prevent class loading by K/N on older iOS where the class does not exist.

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/4644

### CODE REVIEW

**Review by elijah-semyonov — APPROVED** [review]

File: compose/ui/ui-uikit/src/uikitMain/objc/CMPUIKitUtils/CMPUIKitUtils/CMPTextLoupeSession.m [hunk 1]
```diff
@@ -0,0 +1,43 @@
+//
+//  CMPTextLoupeSession.m
+//  CMPUIKitUtils
+//
+//  Created by Andrei.Salavei on 17.04.24.
```
Comment (MatkovIvan) [inline compose/ui/ui-uikit/src/uikitMain/objc/CMPUIKitUtils/CMPUIKitUtils/CMPTextLoupeSession.m]: Please use proper header

Comment (ASalavei) [reply compose/ui/ui-uikit/src/uikitMain/objc/CMPUIKitUtils/CMPUIKitUtils/CMPTextLoupeSession.m]: Thanks! Done.

**Review by MatkovIvan — APPROVED** [review]
