### PR TITLE
Fix crash with disabled textfield in LazyList

### LINKED ISSUE #3559: LazyVerticalGrid scroll: "IllegalStateException: Unknown Modifier.Node type"
**Describe the bug**
Crash when scrolling in a LazyVerticalGrid using OutlinedTextField with alternating enabled flag set.

Happens in 1.5.0-rc02, not 1.4.3.

**Affected platforms**
Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-rc02
- OS version(s): Mac OS 13.5 (22G74) 
- OS architecture (x86 or arm64):  M1 arm64
- JDK (for desktop issues): 11

**To Reproduce**
1. Scroll in LazyVerticalGrid

```
@Composable
@Preview
fun App() {
    MaterialTheme {
        LazyVerticalGrid(
            columns = GridCells.Fixed(4),
            modifier = Modifier.fillMaxSize()
        ) {
            items((0 until 200).toList()) { item ->
                OutlinedTextField(
                    value = "Item: $item",
                    enabled = item % 2 == 0,
                    onValueChange = {},
                )
            }
        }
    }
}
```

**Expected behavior**
No crash

**Screenshots**
Screenshot 2023-08-24 at 13 11 52

### PR DESCRIPTION
**Pull request by igordmn**
Fixed here and cherry-picked to jb-main:
https://android-review.googlesource.com/c/platform/frameworks/support/+/2728094

Fixes https://github.com/JetBrains/compose-multiplatform/issues/3559

### CODE REVIEW

File: compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoLazyListTest.kt [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+import androidx.compose.ui.test.runComposeUiTest
+import androidx.compose.ui.unit.dp
+import kotlin.test.Test
+import kotlin.test.assertTrue
+
+@OptIn(ExperimentalTestApi::class)
+class SkikoLazyListTest {
+    // https://github.com/JetBrains/compose-multiplatform/issues/3559
+    @Test
+    fun textFields() = runComposeUiTest {
```
Comment (eymar) [inline compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoLazyListTest.kt:48]: This test passes even without a fix commit https://github.com/JetBrains/compose-multiplatform-core/commit/d02e1c5c9b79cd481bb57b23ec751b03ce612fcb

Although `enabled` switches betwen true/false.

Is it expected? 

__

The second test fails without the fix commit - that's what is expected

Comment (eymar) [reply compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoLazyListTest.kt:48]: I'm not sure what's going on. I tried to change the test similar to the snippet in the bug report:

```kotlin
    @Test
    fun textFields() = runComposeUiTest {
        val state by mutableStateOf(LazyGridState())
        setContent {
            LazyVerticalGrid(
                state = state,
                columns = GridCells.Fixed(4),
                modifier = Modifier.testTag("list").fillMaxSize()
            ) {
                items((0 until 200).toList()) { item ->
                    BasicTextField(
                        value = "Item: $item",
                        enabled = item % 2 == 0,
                        onValueChange = {},
                    )
                }
            }
        }

        onNodeWithTag("list").performMouseInput {
            scroll(1000f, ScrollWheel.Vertical)
        }
        runOnIdle { assertTrue(state.firstVisibleItemIndex > 0) }
    }
    ```
    
    But it passes without the fix commit anyway.

**Review by eymar — APPROVED** [review]

File: compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoLazyListTest.kt (hunk 1 above)
Comment (igordmn) [reply compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoLazyListTest.kt:48]: Fixed. maybe performMouseInput scrolls to non-crashable state
