### PR TITLE
Fix missing scrolling events

### LINKED ISSUE #3099: Scrolling on both y & x axises is not possible at the same time on compose v1.4.0, but possible in v.1.3.1 and 1.2.2
**Describe the bug**
I noticed a regression in compose-multiplatform 1.4.0 related to scrolls on both the x and y axes. I have a modifier with scrollable arguments. In compose versions 1.2.2 & 1.3.1 I was able to use my touchpad to scroll in both directions simultaneously, but in 1.4.0 it is not possible anymore - only 1 direction at a time.

For slack thread: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1682269433928629

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues):  MacOS Monterey v 12.6.5 (21G531)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): JDK 15 (azul)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Run the following compose in your main
```
@Composable
fun test() {
    var offsetX by remember { mutableStateOf(0f) }
    var offsetY by remember { mutableStateOf(0f) }

    // background
    Box(
        Modifier.fillMaxSize()
            .background(Color.LightGray)
            .scrollable(
                state = ScrollableState {
                    offsetY += it
                    it
                },
                orientation = Orientation.Vertical
            )
            .scrollable(
                state = ScrollableState {
                    offsetX += it
                    it
                },
                orientation = Orientation.Horizontal
            )
    ) {
        // scrollable box
        Box(Modifier
            .requiredSize(200.dp)
            .offset {
                IntOffset(offsetX.roundToInt(), offsetY.roundToInt())
            }
            .background(Color.Blue)
        ) {

        }
    }
}
```
2. Try to use touchpad to scroll in both directions (e.g. diagonally). In compose v1.3.1 you can but in v.1.4.0. you can do it only in one direction, so scrolling becomes jiggish

**Expected behavior**
Should scroll the canvas/box diagonally

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

  - Move `awaitPointerEventScope` outside the loop

## Testing

Test: Use sample from https://github.com/JetBrains/compose-multiplatform/issues/3099

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3099

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt [hunk 1]
```diff
@@ -458,13 +454,11 @@ private suspend fun ScrollingLogic.animatedDispatchScroll(
...
-    onMouseWheel: suspend PointerInputScope.(PointerEvent) -> Boolean
+    onMouseWheel: PointerInputScope.(PointerEvent) -> Boolean
 ) = pointerInput(key1, key2) {
-    coroutineScope {
-        while (isActive) {
-            val event = awaitPointerEventScope {
-                awaitScrollEvent()
-            }
+    awaitPointerEventScope {
+        while (true) {
```
Comment (eymar) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt:460]: Just following the example of some other implementations (like https://github.com/JetBrains/compose-multiplatform-core/blob/32de9dd24cb6eff254b2147d4c8d83e5c2430959/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/ForEachGesture.kt#L100), we can do the following:

```suggestion
    val currentContext = currentCoroutineContext()
    awaitPointerEventScope {
        while (currentContext.isActive) {
```

Otherwise, as I understand, the coroutine may hang (when the modifier gets removed from the composition). It will never receive a continuation anyway, so it probably remains unnoticed. Although, I'm not sure how to test such a behaviour correctly.

Comment (MatkovIvan) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt:460]: Discussed it with @igordmn some time ago. As far as I remember, `awaitPointerEvent` suspends the execution and coroutine can be terminated without explicit checks in this case.

**Review by eymar — APPROVED** [review]
