### PR TITLE
Fix text input popup position

### LINKED ISSUE #2040: Compose 1.2. Check if the input method popup is correctly placed on the screen
In Compose 1.2 [this method](https://github.com/JetBrains/androidx/blob/5f528e84a04008c5c0b037980a5d44ec42d5f0d3/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/DesktopPlatformInput.desktop.kt#L100) was deprecated, and it isn't called from anywhere. This method sets the current position of the text, which is used to position the input method popup.

### LINKED ISSUE #2493: Upgrade compose version from 1.1.1 to 1.3.0-beta02, the TextField of my desktop application could not input any Chinese character
2022-11-23 09:21:27,186 INFO (UncaughtExceptionHandler.kt:53)- java.lang.NullPointerException: Cannot read field "x" because "rc" is null
    at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:617)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

------------------------------------------------------------------------------------------------------------------------------------

When I press the Space and Enter key to input the Chinese character, the application crashed. It is normal when I input english character.

### PR DESCRIPTION
**Pull request by igordmn**
CL: https://android-review.googlesource.com/c/platform/frameworks/support/+/2319924
the only difference with the CL is that we still keep this method Deprecated, to avoid confusion in the future, if we fix this issue another way.

If this CL will be merged, during rebase most probably will be conflicts. Just drop this commit then.

Fixes https://github.com/JetBrains/compose-jb/issues/2040
Fixes https://github.com/JetBrains/compose-jb/issues/2493

notifyFocusedRect was deprecated in https://android-review.googlesource.com/c/platform/frameworks/support/+/1959647

On Android, before deprecation this method was used to scroll to the focused text input.
This functionality was extracted to the text field itself, but we had another functionality on the other platforms.
On Desktop we show text input popup near text input (for some languages):
https://github.com/JetBrains/compose-jb/issues/2040#issuecomment-1333429514

I think that this method is the right choice to implement this functionality, but I am not completely sure. Here my thoughts about alternatives:

1. Use BringIntoViewRequester. Not sure that it is possible, because its purpose - to show the view to the user, not use the passed information to determine the text popup position
2. Get information about focused area from another source that is not related to text input. For example, we can inject FocusManager, and retrieve the focused rect from it. Probably not a good idea, because the rect of arbitrary focused node isn't the same thing as the rect of focused input area.

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt [hunk 1]
```diff
@@ -126,6 +129,57 @@ internal class TextFieldDelegate {
...
+                        textDelegate.fontFamilyResolver
+                    )
+                    Rect(0f, 0f, 1.0f, defaultSize.height.toFloat())
+                }
+            }
+            val globalLT = layoutCoordinates.localToRoot(Offset(bbox.left, bbox.top))
+
+            // TODO remove `Deprecated`, if it is removed in AOSP repository
+            @Suppress("DEPRECATION")
+            textInputSession.notifyFocusedRect(
```
Comment (eymar) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt:178]: Where/how can we observe the focus rect changes? Do we have an API for that?

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt:178]: I didn't found such API, but we can write a new one, if we need. Anyway, it seems if we write something like `LocalFocusManager.focusedRect` it will be not what we want. We want the rect for text input. And here we can get it.

Comment (eymar) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt:178]: What I mean is that I see a few places which call `notifyFocusedRect`, but I don't understand which part actually "observers" the changes so input popup position can be set correctly?

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt:178]: `notifyFocusedRect` subscribed on 2 things:
- `Modifier.onGloballyPositioned` of the text field, which is called every time its repositioned relative to the window.
- `Modifier.onFocusChanged` which triggers when the focus of text field changes.

I realized, that we don't subscribe on cursor changes. We rely on a side effect of `onGloballyPositioned`, which accidentally is called when we change the cursor position (but it seems, it shouldn't). I will investigate, should we also call `notifyFocusedRect` somewhere else.

**Review by eymar — APPROVED** [review]

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt (hunk 1 above)
Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldDelegate.kt:178]: Call it on relayout too now
