### PR TITLE
Fix animation frozen after app went background

### LINKED ISSUE #4566: iOS compose screen freeze when action moves user out of the app
**Describe the bug**
when triggering a navigation action pushing user outside of the app, if user returns again to the same screen, the animation effect that was happening just before the user had left are stuck frozen. 

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.5.12
- OS version(s)* (required for Desktop and iOS issues): ios 16.4, 17.2.1
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): iPhone 14, iPhone XR
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a screen that has a trigger that has animation effect like a button (with ripple effect) or a toggle switcher which navigates the user out of the app
2. trigger the action
3. on returning to the screen, sometimes the trigger animation is stuck frozen

**Expected behavior**
the animation effect should be gone. 
**Screenshots**
Simulator Screenshot - iPhone 14 - 2024-04-01 at 00 29 29
Simulator Screenshot - iPhone 14 - 2024-04-01 at 11 29 57

**Additional context**

### PR DESCRIPTION
**Pull request by elijah-semyonov**
## Proposed Changes

Invalidate compose scene when the app goes foreground to trigger redraw.
The intent is to avoid the situation where last presented frames are discarded due to the app going background, leaving the visual content in older state.

## Testing

Test: Demo/IosBugs/AnimationFreezeBug the visual state always matches the animation final state when app goes to foreground.

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/4566

### CODE REVIEW

**Review by ASalavei — APPROVED** [review]

File: compose/mpp/demo/src/uikitMain/kotlin/androidx/compose/mpp/demo/bugs/AnimationFreezeBug.kt [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import androidx.compose.mpp.demo.Screen
+import androidx.compose.runtime.getValue
+import androidx.compose.runtime.mutableStateOf
+import androidx.compose.runtime.remember
+import androidx.compose.runtime.setValue
+import androidx.compose.ui.Modifier
+import platform.UIKit.UIApplication
+import platform.Foundation.NSURL
+
+val AnimationFreezeBug = Screen.Example("AnimationFreezeBug") {
```
Comment (MatkovIvan) [inline compose/mpp/demo/src/uikitMain/kotlin/androidx/compose/mpp/demo/bugs/AnimationFreezeBug.kt:31]: Can we write the automated test case instead of adding another "bug" page in mpp?

File: compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt [hunk 2]
```diff
@@ -273,6 +274,15 @@ internal class ComposeSceneMediator(
         renderingUIViewFactory(interopContext, renderDelegate)
     }
 
+    private val applicationStateListener = ApplicationStateListener { isForeground ->
+        // Sometimes the application can trigger animation and go background before the animation is
+        // finished. The scheduled GPU work is performed, but no presentation can be done, causing
+        // mismatch between visual state and application state. This can be fixed by forcing
+        // a redraw when app returns to foreground, which will ensure that the visual state is in
+        // sync with the application state even if such sequence of events took a place.
+        onComposeSceneInvalidate()
```
Comment (MatkovIvan) [inline compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt]: it's supposed to be only scene callback. Please call `renderingView.needRedraw()` instead

**Review by MatkovIvan — CHANGES_REQUESTED** [review]

File: compose/mpp/demo/src/uikitMain/kotlin/androidx/compose/mpp/demo/bugs/AnimationFreezeBug.kt (hunk 1 above)
Comment (elijah-semyonov) [reply compose/mpp/demo/src/uikitMain/kotlin/androidx/compose/mpp/demo/bugs/AnimationFreezeBug.kt:31]: No, we can't automate this test. We will lose control of the app once it goes background, no way to bring it back.

File: compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt (hunk 2 above)
Comment (elijah-semyonov) [reply compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt]: Done

**Review by MatkovIvan — APPROVED** [review]
