### PR TITLE
Fix outlined text view regression

### LINKED ISSUE #3737: Regression (1.5.10-beta02): OutlinedTextField label is clipped on iOS
**Describe the bug**
The top of an OutlinedTextField label is clipped when used in an ExposedDropdownMenuBox on iOS. It is not clipped on Android. It was not clipped on iOS until a very recent version, maybe 1.5.10-beta01 or around there.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20-Beta2
- Compose Multiplatform version*: 1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues): iOS 16, 17

**To Reproduce**
```Kotlin
@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun ExposedDropdownMenu3Sample() {
    val options = List(5) { "Item $it" }
    var expanded by remember { mutableStateOf(false) }
    var selectedOptionText by remember { mutableStateOf(options[0]) }
    ExposedDropdownMenuBox(
        expanded = expanded,
        onExpandedChange = { expanded = !expanded },
    ) {
        OutlinedTextField(
            modifier = Modifier.menuAnchor(),
            readOnly = true,
            value = selectedOptionText,
            onValueChange = {},
            label = { Text("ExposedDropdownMenuBox3") },
            trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) },
            colors = ExposedDropdownMenuDefaults.textFieldColors(),
        )
        ExposedDropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
        ) {
            options.forEach { selectionOption ->
                DropdownMenuItem(
                    text = { Text(selectionOption) },
                    onClick = {
                        selectedOptionText = selectionOption
                        expanded = false
                    },
                    contentPadding = ExposedDropdownMenuDefaults.ItemContentPadding,
                )
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by elijah-semyonov**
## Proposed Changes

Construct `OverscrollEffect` outside of `textFieldScrollable` and pass it there to keep scroll behavior similar to iOS (the only platform providing text field overscroll for now)
Use the `OverscrollEffect.effectModifier` (if any) for internal text and not decoration box itself to avoid unintended clipping.

## Testing

Test: check that `OutlinedTextField` is not incorrectly clipped. `OverscrollEffect` for large text fields still works correctly.

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3737

### CODE REVIEW

File: compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/textfield/TextFields.kt [hunk 1]
```diff
@@ -59,6 +57,17 @@ val TextFields = Screen.Selection(
             FastDelete()
         }
     },
+    Screen.Example("OutlinedTextField") {
```
Comment (MatkovIvan) [inline compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/textfield/TextFields.kt]: It was added in #850, no need to add one more page

**Review by dima-avdeev-jb — APPROVED** [review]
