### PR TITLE
Fix scrolling when we change LazyListState

### LINKED ISSUE #3551: LazyColumn is not scrollable when reinitializing its LazyListState and wasn't scrollable before
**Describe the bug**

Before 1.5.0 (tested with rc01 and r04), you could change the state of the LazyColumn without any issues, but now it stops scrolling if the previous data was not scrollable (works fine in 1.4.3). Here is a minimal version of the bug found in [Gitnuro](https://github.com/JetpackDuba/Gitnuro/):

```
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyListState
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.window.singleWindowApplication
import com.jetpackduba.gitnuro.ui.components.ScrollableLazyColumn
import kotlinx.coroutines.flow.MutableStateFlow

fun main() {
    val lazyListStateFlow = MutableStateFlow(
        LazyListState(firstVisibleItemIndex = 0, firstVisibleItemScrollOffset = 0)
    )

    val numbersFlow = MutableStateFlow(emptyList<Int>())

    singleWindowApplication {
        val listState by lazyListStateFlow.collectAsState()
        val numbers by numbersFlow.collectAsState()

        Column {
            Button(
                onClick = {
                    numbersFlow.value = (0 until 10).toList()
                    lazyListStateFlow.value = LazyListState(firstVisibleItemIndex = 0, firstVisibleItemScrollOffset = 0)
                }
            ) {
                Text("10 items")
            }
            Button(
                onClick = {
                    numbersFlow.value = (0 until 100).toList()
                    lazyListStateFlow.value = LazyListState(firstVisibleItemIndex = 0, firstVisibleItemScrollOffset = 0)
                }
            ) {
                Text("100 items")
            }

            ScrollableLazyColumn(modifier = Modifier.fillMaxSize(), state = listState) {
                items(numbers) {
                    Text(it.toString())
                }
            }
        }
    }
}

```

ScrollableLazyColumn component is just this:

```
@Composable
fun ScrollableLazyColumn(
    modifier: Modifier,
    state: LazyListState = rememberLazyListState(),
    content: LazyListScope.() -> Unit
) {
    Box(
        modifier = modifier,
    ) {
        LazyColumn(
            state = state,
            content = content
        )
        VerticalScrollbar(
            modifier = Modifier
                .align(Alignment.CenterEnd)
                .fillMaxHeight()
                .padding(end = 2.dp),
            style = LocalScrollbarStyle.current.copy(
                unhoverColor = MaterialTheme.colors.scrollbarNormal,
                hoverColor = MaterialTheme.colors.scrollbarHover,
            ),
            adapter = rememberScrollbarAdapter(
                scrollState = state
            )
        )
    }
}
```

When dragging using the scrollbar it works just fine, but not with the mouse.

Works fine on Android.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.7.10
- Compose Multiplatform version*:   1.5.0-rc04
- OS version(s)* (required for Desktop and iOS issues): Archlinux (up to date) & Ubuntu 22.04.3
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): Amazon Corretto 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Click on the "10 items" button.
2. Click on the "100 items" button.
3. Try to scroll the list (Nothing happens)
4. Close the app
5. Click on the "100 items" button.
6. Try to scroll the list (It works)

**Expected behavior**
It should be scrollable whenever there are enough items, as happens with the scrollbar.

### PR DESCRIPTION
**Pull request by igordmn**
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3551

When the new state is passed to LazyList, it goes down to `Modifier.pointerScrollable` as `controller: ScrollableState`, and wraps to `rememberUpdatedState`, which is always the same instance. Because it is the same instance, MouseWheelScrollableElement.update is never called.

Passing it is as a value now, as MouseWheelScrollableElement doesn't need a state.

## Testing

- Run SkikoScrollableTest
- Run the snippet from the issue

### CODE REVIEW

File: compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoScrollableTest.kt [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+@OptIn(ExperimentalTestApi::class)
+class SkikoScrollableTest {
+    // bug https://github.com/JetBrains/compose-multiplatform/issues/3551 (mouse didn't work)
+    @Test
+    fun recreating_list_state_shouldn_t_break_mouse_scrolling() = runComposeUiTest {
+        var state by mutableStateOf(LazyListState())
+        setContent {
+            LazyColumn(state = state, modifier = Modifier.testTag("list").fillMaxSize()) {
+                items(1000) {
```
Comment (eymar) [inline compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoScrollableTest.kt:49]: Sorry, I can't run the tests right now to check:
Does this test reproduce the original issue?
In the original issue it scrolls fine when 100 items added from the start. But it didn't work when first 10 added and then 100 added afterwards. 
And here the test adds 1000 from the beginning. 

Or the items count doesn't matter, because what matters is the LazyListState change?

**Review by eymar — APPROVED** [review]

File: compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoScrollableTest.kt (hunk 1 above)
Comment (igordmn) [reply compose/foundation/foundation/src/skikoTest/kotlin/androidx/compose/foundation/gestures/SkikoScrollableTest.kt:49]: Yes, it reproduces the orignal issue. It was not because we change items, but because we change the state.

I rechecked the original code - it is fixed.

Also, looking at the failed test now

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt [hunk 2]
```diff
@@ -283,13 +283,39 @@ private fun Modifier.pointerScrollable(
...
-        .then(MouseWheelScrollableElement(scrollLogic, scrollConfig, density))
+        .then(MouseWheelScrollableElement(scrollLogicValue, scrollConfig, density))
         .nestedScroll(nestedScrollConnection, nestedScrollDispatcher.value)
 }
 
 // {} isn't being memoized for us, so extract this to make sure we compare equally on recomposition.
 private val NoOpOnDragStarted: suspend CoroutineScope.(startedPosition: Offset) -> Unit = {}
 
+@Composable
+private fun rememberScrollingLogic(
```
Comment (igordmn) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt:294]: It seems there is test that checks equality of the modifier across compositions. Probably for optimization. `remember` fixes the test.

Remembering scrolling logic seems logical here, and shouldn't add overhead.

In 1.6 it was fully rewritten to modifier node:

https://github.com/androidx/androidx/blob/a7e6bdf524be186baca08e9ddf7272b834a14bd2/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt#L276

Comment (eymar) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt:294]: which test was failing before adding `rememberScrollingLogic` ?

**Review by eymar — APPROVED** [review]
LGTM. The tests passed on my machine too.

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt (hunk 2 above)
Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt:294]: [This one](https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_DesktopTestsForPullRequests/4287964?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandPull+Request+Details=true&expandBuildTestsSection=true)
