### PR TITLE
Fix web datepicker text field illegal input crash

### LINKED ISSUE #4856: [Web] Uncaught runtime error in Material3 DatePicker (DisplayMode.Input) when enter incorrect date
**Describe the bug**
There is a crash (runtime error DateTimeException) when you use `material3.DatePicker` in `DisplayMode.Input` and enter incorrect date like `50/50/2024`. Only reproduces in Web, all other targets work correctly.

**Affected platforms**

- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.1, 1.6.10
- Kotlin version: 1.9.23, 2.0.0

**To Reproduce**
1. Run this code snippet:
   ```kt
   @Composable
   fun BugReproduction() {
       Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
           val state = rememberDatePickerState(initialDisplayMode = DisplayMode.Input)
           DatePicker(state = state)
       }
   }
   ```
2. Enter 50/50/2024 date
3. See error

**Expected behavior**
There should be no crash but the error tip like "Date does not match expected pattern" like on all other platforms

**Screenshots**
Web crash: 
Screenshot 2024-05-23 at 11 16 28

Desktop ok: 
Screenshot 2024-05-23 at 11 17 15

### PR DESCRIPTION
**Pull request by alexzhirkevich**
- Update kotlinx.datetime to [0.6.0](https://github.com/Kotlin/kotlinx-datetime/releases/tag/v0.6.0)
- Migrate locale-invariant web formatting/parsing to kotlinx.datetime
- Catch parsing exceptions

Fixes https://github.com/JetBrains/compose-multiplatform/issues/4856

## Testing
`KotlinxDatetimeCalendarModelTest.illegalDateParsingDoesNotThrowException`

This should be tested by QA

### Fixes - Web
- Fixed crash when date picker text field receives illegal input

### CODE REVIEW

File: compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt [hunk 1]
```diff
@@ -123,7 +123,9 @@ internal class KotlinxDatetimeCalendarModel(locale: CalendarLocale) : CalendarMo
     }
 
     override fun parse(date: String, pattern: String): CalendarDate? {
-        return platformDateFormat.parse(date, pattern)
+        return kotlin.runCatching {
```
Comment (eymar) [inline compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: It looks like parsing exceptions handling is present in the implementations of `platformDateFormat` (For example: https://github.com/JetBrains/compose-multiplatform-core/blob/797ab9e20fb33920d600226324cc293d97561d3b/compose/material3/material3/src/jvmMain/kotlin/androidx/compose/material3/LegacyCalendarModelImpl.jvm.kt#L148). 

So it would make it wrapped in try/catch twice.
What do you think about moving this try/catch to web implementation? (webCommonW3C sourceset). 
So it would make it conform its behaviour to the implementations on other platforms.

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Sounds reasonable. Done

**Comment by alexzhirkevich** [comment]
Do you known why iOS CI runs here instead of web?

**Comment by eymar** [comment]
> Do you known why iOS CI runs here instead of web?

it seems that iOS tests run for all changes, regardless of the where the change was added.
web tests should run eventually too (they run on teamcity).

**Comment by alexzhirkevich** [comment]
> it seems that iOS tests run for all changes, regardless of the where the change was added.

Expensive macos runners aren't happy about that 😆

**Comment by eymar** [comment]
anyway, in this case skikoTest was changed and the library version was updated, so it would make sense for iOS tests to run. And ideally to pass... But, CI doesn't want to generate the test report :D

**Review by eymar — APPROVED** [review]
The tests passed locally on all platforms.

Thank you for this contribution :)
