### PR TITLE
Fix SkikoComposeUiTest.isIdle

### LINKED ISSUE #3117: DesktopComposeTestRule.waitForIdle() can return even though the compose state isn't idle
**Describe the bug**

Because of GlobalSnapshotManager calling `Snapshot.sendApplyNotifications()` which immediately advances the snapshot but takes some time to send the notifications, `DesktopComposeTestRule.isIdle()` can return false before the apply notifications have been sent (`Snapshot.current.hasPendingChanges()` already returns false but `scene.hasInvalidations()` still returns false).

**Versions**
- Compose Multiplatform version: 1.4.x

**To Reproduce**
```
    @Test
    fun idleIsReallyIdle() = repeat(300){
        val globalValue = AtomicInteger()
        rule.setContent {
            var localValue by remember{ mutableStateOf(0) }

            remember(localValue) {
                globalValue.set(localValue)
            }

            Layout(
                {},
                Modifier.size(50.dp),
                measurePolicy = { _, constraints ->
                    localValue = 100
                    layout(constraints.maxWidth, constraints.maxHeight) {}
                }
            )
        }

        assertEquals(100, globalValue.get())
    }
```

**Expected behavior**
`rule.setContent` calls `waitForIdle` before returning, therefore `globalValue` should be 100 when that happens. In reality, it ends up remaining 0 every once in a while (hence the `repeat(300)`.

**Additional context**
A solution suggested by Chuck from Google, which we're working on, is to add a counter of "current callers inside `Snapshot.advanceGlobalSnapshot`" which would allow `isIdle()` to detect the transitional state when the apply notifications haven't been sent yet.

### PR DESCRIPTION
**Pull request by m-sasha**
Currently, when `Snapshot.isApplyObserverNotificationPending` is being called concurrently with the test thread (which GlobalSnapshotManager typically does), `SkikoComposeUiTest.isIdle` can return true because the snapshot changes have already been cleared (`Snapshot.current.hasPendingChanges()` already returns false), but `ComposeScene` hasn't received the notification(s) yet (`scene.hasInvalidations()` still returns false).

This breaks unit tests which set up a scene and expect it to be idle/stable when `setContent` or `waitForidle` returns.

## Proposed Changes

Fix `SkikoComposeUiTest.isIdle` to return false when `Snapshot.sendApplyNotifications` is running (via the new `Snapshot.isApplyObserverNotificationPending` property).

## Testing

Test: new unit test

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3117

### CODE REVIEW

File: compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/ComposeUiTestTest.kt [hunk 1]
```diff
@@ -126,6 +129,35 @@ class ComposeUiTestTest {
         }
     }
 
+    // See https://github.com/JetBrains/compose-multiplatform/issues/3117
+    // Note: this test is under desktopTest instead of skikoTest because there's no access to
+    // atomics in skikoTest
+    @Test
+    fun recompositionCompletesBeforeSetContentReturns() = repeat(300){
```
Comment (MatkovIvan) [inline compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/ComposeUiTestTest.kt]:
```suggestion
    fun recompositionCompletesBeforeSetContentReturns() = repeat(300) {
```

File: compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/ComposeUiTestTest.kt [hunk 2]
```diff
@@ -126,6 +129,35 @@ class ComposeUiTestTest {
         }
     }
 
+    // See https://github.com/JetBrains/compose-multiplatform/issues/3117
+    // Note: this test is under desktopTest instead of skikoTest because there's no access to
+    // atomics in skikoTest
```
Comment (MatkovIvan) [inline compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/ComposeUiTestTest.kt]: There are a few expect/actual in the repo for `AtomicInt`: It's a typealias to `java.util.concurrent.atomic.AtomicInteger`on jvm and to `kotlin.native.concurrent.AtomicInt` on k/native

Comment (m-sasha) [reply compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/ComposeUiTestTest.kt]: It's `internal`, unfortunately. The `expect` is public (because of some bug), but the `actual`s are internal.

**Review by MatkovIvan — APPROVED** [review]

File: compose/ui/ui-test-junit4/src/skikoTest/kotlin/androidx/compose/ui/test/ComposeUiSkikoTestTest.kt [hunk 3]
```diff
@@ -429,6 +427,33 @@ class ComposeUiSkikoTestTest {
         onNodeWithTag("test").performTextClearance()
         assertThat(text.text).isEqualTo("")
     }
+
+    // See https://github.com/JetBrains/compose-multiplatform/issues/3117
+    @Test
+    fun recompositionCompletesBeforeSetContentReturns() = repeat(300) {
```
Comment (eymar) [inline compose/ui/ui-test-junit4/src/skikoTest/kotlin/androidx/compose/ui/test/ComposeUiSkikoTestTest.kt]: I tried to run this test as is but without the fix - "isApplyObserverNotificationPending" to reproduce the issue. It didn't fail on my linux machine - I made ~10 attempts. Then I increased the repeat to 3000 and it fails on each run attempt after ~1k iterations.With the fix it works fine with 3k iterations.

Did it fail for you with 300 iterations? Is it worth to increase the number of iterations to make this test less flaky in case `isIdle` implementation changes for some reason later?

**Review by eymar — APPROVED** [review]

File: compose/ui/ui-test-junit4/src/skikoTest/kotlin/androidx/compose/ui/test/ComposeUiSkikoTestTest.kt (hunk 3 above)
Comment (m-sasha) [reply compose/ui/ui-test-junit4/src/skikoTest/kotlin/androidx/compose/ui/test/ComposeUiSkikoTestTest.kt]: It fails pretty consistently for me at 300, but let's make it 1000 just in case.
