### PR TITLE
Fix owner's `isInBounds` check

### LINKED ISSUE #4123: Tooltips and at least some forms of hover don't work in IntelliJ on 1.6
**Describe the bug**
```kotlin
TooltipArea({ BasicText("Tooltip", Modifier.background(Color.Magenta).padding(8.dp)) }) {
    BasicText("Hover here", Modifier.background(Color.Gray).padding(8.dp))
}
```

This doesn't show any tooltip in IJ, but works in standalone apps. It looks like in general hover doesn't work in the IDE anymore. Tested on 23.3.2 on macOS.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.21
- Compose Multiplatform version*: 1.6.0-dev1362
- OS version(s)* (required for Desktop and iOS issues): macOS 14.2.1
- OS architecture (x86 or arm64): aarch64
- JDK (for desktop issues): 17.0.9+7-b1087.9 aarch64 OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

- Use window coordinates to check if it's in bounds - it's different after #956

## Testing

Test: run added unit test or the next sample:
```kt
fun main() = SwingUtilities.invokeLater {
    SwingComposeWindow()
}

fun SwingComposeWindow() {
    val window = JFrame()
    window.defaultCloseOperation = WindowConstants.EXIT_ON_CLOSE

    val panel = JPanel()
    panel.layout = GridLayout(2, 1)
    panel.add(JPanel())
    panel.add(ComposePanel().apply {
        setContent {
            ComposeContent(background = Color.Green)
        }
    })
    window.contentPane.add(panel, BorderLayout.CENTER)

    window.setSize(800, 600)
    window.isVisible = true
}

@OptIn(ExperimentalFoundationApi::class)
@Composable
fun ComposeContent(background: Color) {
    Box(
        modifier = Modifier.fillMaxSize().background(color = background),
        contentAlignment = Alignment.Center
    ) {

        TooltipArea({ BasicText("Tooltip", Modifier.background(Color.Magenta).padding(8.dp)) }) {
            BasicText("Hover here", Modifier.background(Color.Gray).padding(8.dp))
        }
    }
}
```

## Issues Fixed

Fixes https://github.com/JetBrains/compose-multiplatform/issues/4123

### CODE REVIEW

File: compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/awt/ComposePanelTest.kt [hunk 1]
```diff
@@ -360,4 +366,46 @@ class ComposePanelTest {
             }
         }
     }
+
+    @Test
```
Comment (m-sasha) [inline compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/awt/ComposePanelTest.kt:371]: Perhaps explain what this tests, and add a link to the github issue.

**Review by m-sasha — APPROVED** [review]

File: compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/awt/ComposePanelTest.kt (hunk 1 above)
Comment (MatkovIvan) [reply compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/awt/ComposePanelTest.kt:371]: Done
