### PR TITLE
Fix nested scrolling on mouse wheel

### LINKED ISSUE #653: Desktop: Nested scrolling is not working properly
NestedScrollConnectionSample from compose samples [(link)](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/ui/ui/samples/src/main/java/androidx/compose/ui/samples/NestedScrollSamples.kt) is not working on desktop - toolbar suppose to move away when scrolling. Here in the sample onPreScroll method is never called. The sample works fine when run on Android.

```Kotlin
@Composable
fun NestedScrollConnectionSample() {
    // here we use LazyColumn that has build-in nested scroll, but we want to act like a
    // parent for this LazyColumn and participate in its nested scroll.
    // Let's make a collapsing toolbar for LazyColumn
    val toolbarHeight = 48.dp
    val toolbarHeightPx = with(LocalDensity.current) { toolbarHeight.roundToPx().toFloat() }
    // our offset to collapse toolbar
    val toolbarOffsetHeightPx = remember { mutableStateOf(0f) }
    // now, let's create connection to the nested scroll system and listen to the scroll
    // happening inside child LazyColumn
    val nestedScrollConnection = remember {
        object : NestedScrollConnection {
            override fun onPreScroll(available: Offset, source: NestedScrollSource): Offset {
                // try to consume before LazyColumn to collapse toolbar if needed, hence pre-scroll
                val delta = available.y
                val newOffset = toolbarOffsetHeightPx.value + delta
                toolbarOffsetHeightPx.value = newOffset.coerceIn(-toolbarHeightPx, 0f)
                // here's the catch: let's pretend we consumed 0 in any case, since we want
                // LazyColumn to scroll anyway for good UX
                // We're basically watching scroll without taking it
                return Offset.Zero
            }
        }
    }
    Box(
        Modifier
            .fillMaxSize()
            // attach as a parent to the nested scroll system
            .nestedScroll(nestedScrollConnection)
    ) {
        // our list with build in nested scroll support that will notify us about its scroll
        LazyColumn(contentPadding = PaddingValues(top = toolbarHeight)) {
            items(100) { index ->
                Text("I'm item $index", modifier = Modifier.fillMaxWidth().padding(16.dp))
            }
        }
        TopAppBar(
            modifier = Modifier
                .height(toolbarHeight)
                .offset { IntOffset(x = 0, y = toolbarOffsetHeightPx.value.roundToInt()) },
            title = { Text("toolbar offset is ${toolbarOffsetHeightPx.value}") }
        )
    }
}
```

Library version: 0.4.0-build182
OS: MacOS

### LINKED ISSUE #1423: LazyListState.isScrollInProgress is always false on desktop
Compose-jb version: 1.0.0-beta5
kotlin version: 1.5.31
Hi,  I want to save the first item position after scroll,  here is my code:
```kotlin
            MaterialTheme {
                val listState = rememberLazyListState()
                LaunchedEffect(Unit) {
                    snapshotFlow { listState.isScrollInProgress }
                        .distinctUntilChanged()
                        .filter {
                            println("is scroll in Progress:$it")
                            !it
                        }.collect {
                            //save state here..
                        }
                }
                LazyColumn(state = listState) {
                    items(500) { index ->
                        Text("Test item $index")
                    }
                }
            }
```
it works perfect on Android, isScrollInProgress updated  every time the list start to scroll and stop scroll
```
2021-11-19 14:26:37.012 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:26:37.495 16032-16032/? I/System.out: is scroll in Progress:false
2021-11-19 14:26:37.860 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:26:39.333 16032-16032/? I/System.out: is scroll in Progress:false
2021-11-19 14:26:58.640 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:27:00.484 16032-16032/? I/System.out: is scroll in Progress:false
```
But on desktop (MacOS BigSur/ Windows10) I found that  isScrollInProgress ```is always false``` even list is clearly in scroll。BTW， I've tested this code both on my project and Compose-jb/examples/imageViewer, the results is the same.

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

- Use `dispatchScroll` with a new `NestedScrollSource.Wheel` instead of direct call of `scrollBy`/`dispatchRawDelta`
- Set scrolling priority to `MutatePriority.UserInput` during mouse wheel scroll animation
- Move all scroll delta dispatching into a single coroutine
- Remove threshold (logic where small delta was applied without animation), `shouldApplyImmediately` flag based on `isPreciseWheelScroll` handles it instead.
- Wait `ProgressTimeout` after each mouse wheel event before resetting `isScrollInProgress` flag
- Enable this logic by default (old "raw" dispatching failed our tests on iOS)

## Testing

Test: Check "NestedScroll" page in mpp demo + unit tests

## Issues Fixed

Fixes https://github.com/JetBrains/compose-multiplatform/issues/653
Fixes https://github.com/JetBrains/compose-multiplatform/issues/1423

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt [hunk 1]
```diff
@@ -229,13 +230,13 @@ private class AnimatedMouseWheelScrollPhysics(
         var requiredAnimation = true
         var lastValue = 0f
         val anim = AnimationState(0f)
-        while (requiredAnimation) {
+        while (requiredAnimation && coroutineScope.isActive) {
```
Comment (igordmn) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt]:
```suggestion
        while (requiredAnimation && coroutineContext.isActive) {
```

We can wrap this suspend function into another `coroutineScope { }` in the future. Better to be safe.

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt [hunk 2]
```diff
@@ -130,36 +133,28 @@ private class RawMouseWheelScrollPhysics(
...
-    override fun PointerInputScope.onMouseWheel(pointerEvent: PointerEvent): Boolean {
-        val scrollDelta = with(mouseWheelScrollConfig) {
-            calculateMouseWheelScroll(pointerEvent, size)
-        }
-        return if (mouseWheelScrollConfig.isPreciseWheelScroll(pointerEvent)) {
-            // In case of high-resolution wheel, such as a freely rotating wheel with no notches
-            // or trackpads, delta should apply directly without any delays.
-            scrollingLogic.dispatchRawDelta(scrollDelta) != Offset.Zero
+    private fun ScrollingLogic.dispatchPreciseWheelScroll(scrollDelta: Offset) {
+        coroutineScope.launch {
```
Comment (igordmn) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt]: This most probably causes input lags and junks on macOs:

https://github.com/JetBrains/compose-multiplatform-core/assets/5963351/b4c1a2ae-5411-46c1-9e71-a33e180101a5

left - the new implementation, right - the old one

(from https://github.com/JetBrains/compose-multiplatform-core/tree/ivan.matkov/fix-nested-scroll-compare-with-old).

cc @m-sasha let's discuss tomorrow a possible fix. We should flush coroutines not only from composition, but from events as well.

Until then, we can't merge the PR. After fixing, we can merge the PR as it is if the junks are fixed.

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt]: I investigated if this helps to remove junks:
```
Subject: [PATCH] -
---
Index: compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/BaseComposeScene.skiko.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/BaseComposeScene.skiko.kt b/compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/BaseComposeScene.skiko.kt
--- a/compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/BaseComposeScene.skiko.kt	(revision da04be1b94c73ebace27a96766f3b84048342e09)
+++ b/compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/BaseComposeScene.skiko.kt	(date 1707517409453)
@@ -159,6 +159,7 @@
         // dispatched, in order to allow registering for these events before they are sent.
         // Otherwise, events like a synthetic mouse-enter sent due to a new element appearing under
         // the pointer would be missed by e.g. InteractionSource.collectHoverAsState
+        recomposer.performScheduledEffects()     // Composition effects (e.g. LaunchedEffect)
         recomposer.performScheduledTasks()
         frameClock.sendFrame(nanoTime)           // Recomposition
         doLayout()                               // Layout
```
It doesn't help unfortunately. I need to compare timings of events and frames to remove subjectivity, and understand the reason.

**Review by igordmn — APPROVED** [review]
