### PR TITLE
Correctly support Arrangement.spacedBy in ScrollbarAdapters for lazy lists/grids

### LINKED ISSUE #2644: Scrollbar works incorrectly with lazy list that uses Arrangement.spacedBy
It appears the spacing between the items is not accounted for.

```
import androidx.compose.foundation.VerticalScrollbar
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollbarAdapter
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState


fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "Experiments",
        state = rememberWindowState(width = 300.dp, height = 380.dp)
    ) {
        LazyScrollable()
    }
}


@Composable
private fun LazyScrollable() {
    Box(
        modifier = Modifier.fillMaxSize()
            .background(color = Color.White)
    ) {

        val state = rememberLazyListState()

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            verticalArrangement = Arrangement.spacedBy(24.dp),
            state = state,
        ) {
            items(20) { x ->
                TextBox("Item #$x", x)
            }
        }
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = rememberScrollbarAdapter(
                scrollState = state,
            )
        )
    }
}
```

https://user-images.githubusercontent.com/5230206/213001195-40dbe1d5-12df-4717-9b7a-654c9252c96a.mp4

You can see the scrollbar lagging more and more behind the mouse cursor, and is unable to reach the bottom.

### PR DESCRIPTION
**Pull request by m-sasha**
## Proposed Changes

  - Add `mainAxisItemSpacing` property to LazyListLayoutInfo, LazyGridLayoutInfo and LazyStaggeredGridLayoutInfo, per discussion with Andrey Kulikov from Google.
  - Use the new `mainAxisItemSpacing` property to fix the line size approximation in `LazyListScrollbarAdapter` and `LazyGridScrollbarAdapter`

## Testing

Test: manually and with a new unit test

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-jb/issues/2644

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt [hunk 1]
```diff
@@ -147,4 +153,5 @@ internal object EmptyLazyStaggeredGridLayoutInfo : LazyStaggeredGridLayoutInfo {
     override val viewportEndOffset: Int = 0
     override val beforeContentPadding: Int = 0
     override val afterContentPadding: Int = 0
+    override val mainAxisItemSpacing: Int = 0
```
Comment (igordmn) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt]: Better to wait for https://android-review.googlesource.com/c/platform/frameworks/support/+/2397134 to merge, and then cherry-pick it straight into `jb-main`

**Review by igordmn — APPROVED** [review]

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt (hunk 1 above)
Comment (m-sasha) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt]: Done. The cherry-pick is part of this PR, so you can review it too.
Once approved, I will `merge --ff-only` this branch into `jb-main`, to avoid squashing the two commits.

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt]: Let's push the cherry-pick straight into jb-main.

The alternative process is as you described. It is better because we review everything that adds to the main branch, but worse because:
1. we have to enable merging of PR's. If we do that, someone can use it, and don't bother about commits in the PR. It will spoil the git history.
2. the review of a cherry-pick and a fix together is harder than just fixes.
3. the 2. can be fixed by squashing the fix into a single commit, but it requires force-push, that is also not good for review.

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt]: On the other hand, we also lose ability to run CI (we'll configure it in the future) on the cherry-pick.

And one more issue. When it will be merged, the code is become common. And when users tried to use it, they encounter noSuchMethod on Android. I don't know good way to solve it. We have 2 options:
1. wait for the Jetpack release, and point to it in our sources. But if it will be 1.5, we can't merge it right now
2. make public API internal, fix conflicts later (we should add comments near internal to describe how to solve conflicts)

Comment (m-sasha) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/staggeredgrid/LazyStaggeredGridMeasureResult.kt]: I'll adjust the cherry-picked commit to make the new properties `internal` for now.

**Review by igordmn — APPROVED** [review]
