### PR TITLE
Fix selection merge

### LINKED ISSUE #2899: Text selection doesn't work correctly in Codeviewer
**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: `1.3.1`
- OS version(s)* (required for Desktop and iOS issues): macOS

**To Reproduce**
1. Run examples/codeviewer (`./gradlew run`)
1. Try to select text starting from empty line
1. Only 1 line can be selected

**Expected behavior**
Text is selecting to the cursor

**Screenshots**

https://user-images.githubusercontent.com/1836384/226384996-b849308f-60cd-4e8b-b634-d50dba34568b.mov

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

Proper merging of selected ranges

## Testing

1. Run examples/codeviewer (`./gradlew run`)
1. Try to select text starting from empty line
1. Only 1 line can be selected

## Issues Fixed

Fixes https://github.com/JetBrains/compose-multiplatform/issues/2899

### CODE REVIEW

File: compose/foundation/foundation/src/test/kotlin/androidx/compose/foundation/text/selection/SelectionTest.kt [hunk 1]
```diff
@@ -70,147 +70,118 @@ class SelectionTest {
...
-            offset = endOffset2,
-            selectableId = selectableKey2
-        )
-        val selection2 = Selection(
-            start = startAnchor2,
-            end = endAnchor2,
-            handlesCrossed = false
-        )
-
+        val selection1 = makeSelection(9, 20, 1L, false)
```
Comment (eymar) [inline compose/foundation/foundation/src/test/kotlin/androidx/compose/foundation/text/selection/SelectionTest.kt:73]: Just to be sure I don't miss some detail: the tests check the same logic as before the change? The change here is just a refactoring + new tests for the fix?

Comment (eymar) [reply compose/foundation/foundation/src/test/kotlin/androidx/compose/foundation/text/selection/SelectionTest.kt:73]: While the refactoring is absolutely a good thing to do, we need to consider the following nuances:
This code is in the common source set, so the changes may come from the upstream later and there would be one more place with possible conflict. To overcome this, we can upstream this PR (not urgent, just to decide the next steps for ourselves). 
Another option is to postpone the  tests refactoring.
Although the fix is useful for android too, so eventual upstreaming would be good

Comment (MatkovIvan) [reply compose/foundation/foundation/src/test/kotlin/androidx/compose/foundation/text/selection/SelectionTest.kt:73]: > Just to be sure I don't miss some detail: the tests check the same logic as before the change? The change here is just a refactoring + new tests for the fix?

Yep

**Review by eymar — APPROVED** [review]
