### PR TITLE
Handle scroll cancellation exception

### LINKED ISSUE #3366: Scrolling LazyColumn via mouse wheel stops working
**Describe the bug**
Scrolling lazy list via mouse wheel while new elements are added to the list and _scrollToItem_ method is called on _LazyListState_, breaks scrolling via mouse wheel.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.0 
- Compose Multiplatform version*:  v1.4.0, v1.4.1 (NOT reproducible with v1.3.1)
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): 15, 17

**To Reproduce**
Minimal reproducible example:

```kotlin
import androidx.compose.material.MaterialTheme
import androidx.compose.foundation.VerticalScrollbar
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollbarAdapter
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@Composable
fun App(myStringList: List<String>) {
    MaterialTheme {
        Column(modifier = Modifier.fillMaxSize()) {
            var scrollToBottomEnabled by remember { mutableStateOf(false) }

            // Button used to control scroll-to-bottom feature
            Button(onClick = {scrollToBottomEnabled = !scrollToBottomEnabled}) {
                Text(if (!scrollToBottomEnabled) "Enable auto-scroll" else "Disable auto-scroll")
            }

            Box(modifier = Modifier.fillMaxSize()) {
                val state = rememberLazyListState()

                if (scrollToBottomEnabled) {
                    // Standard approach to implement scroll-to-bottom feature 
                    LaunchedEffect(myStringList.size) {
                        state.scrollToItem(myStringList.size - 1)
                    }
                }

                LazyColumn(Modifier.fillMaxSize(), state) {
                    items(items = myStringList) {
                        Text(it)
                    }
                }

                VerticalScrollbar(
                    modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
                    adapter = rememberScrollbarAdapter(scrollState = state)
                )

            }
        }
    }
}

fun main() = application {
    val myStringList = mutableStateListOf<String>()

    // Coroutine which keeps adding elements into the myStringList
    CoroutineScope(Dispatchers.Default).launch {
        var someInt = 0

        while (true) {
            delay(50)
            myStringList.add("Element $someInt")
            someInt += 1
        }
    }

    Window(onCloseRequest = ::exitApplication) {
        App(myStringList)
    }
}

```
1. Run minimal reproducible example using Compose v1.4.0 or v1.4.1 
2. Use mouse wheel to scroll the list to make sure it is working fine by default
3. Click on button: "Enable auto-scroll"
4. Try to scroll the list using mouse wheel
5. Click on button: " Disable auto-scroll"
6. Try to scroll the list using mouse wheel

**Expected behavior**
It should be possible to scroll the list using mouse wheel.

**Actual behavior**
Using mouse wheel doesn't scroll the list. The list can still be scrolled by moving vertical scrollbar via mouse.

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

`scroll` block can be interrupted by other scroll animation or manual input. Handling wheel input cycle shouldn't be interrupted by that.

PS review with whitespace ignored

## Testing

Test: run mpp `LazyColumn` sample

## Issues Fixed

Fixes https://github.com/JetBrains/compose-multiplatform/issues/3366

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt [hunk 1]
```diff
@@ -146,11 +147,14 @@ private class AnimatedMouseWheelScrollNode(
             while (isActive) {
                 val event = channel.receive()
                 isAnimationRunning = true
-                scrollingLogic.animatedDispatchScroll(event, speed = 1f * density) {
-                    // Sum delta from all pending events to avoid multiple animation restarts.
-                    channel.sumOrNull()
+                try {
+                    scrollingLogic.animatedDispatchScroll(event, speed = 1f * density) {
```
Comment (elijah-semyonov) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:151]: 1f seems redundant

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt [hunk 2]
```diff
@@ -229,38 +233,42 @@ private class AnimatedMouseWheelScrollNode(
...
-                    sequentialAnimation = true
-                ) {
-                    val delta = value - lastValue
-                    if (!delta.isLowScrollingDelta()) {
-                        val consumedDelta = scrollBy(delta)
-                        if (!(delta - consumedDelta).isLowScrollingDelta()) {
+        var requiredAnimation = true
+        var lastValue = 0f
+        val anim = AnimationState(0f)
+        while (requiredAnimation) {
```
Comment (igordmn) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:239]: Shouldn't we keep `while` inside `scroll`? To cancel our mouse wheel animation completely, when something starts to scroll the list programmatically

Comment (MatkovIvan) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:239]: It was my first try, but no - this way we lose not consumed delta

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:239]: Semantically, we need to stop the animation. Can you explain the issue more? May be we can stop the animation, but fix the issue another way.

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:239]: > Semantically, we need to stop the animation. 

Discussed that if we stop the animations soon, we'll see sharp unsmooth scroolling (if there are 2 scrolls involved)

**Review by igordmn — APPROVED** [review]

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt (hunk 2 above)
Comment (MatkovIvan) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:239]: > Semantically, we need to stop the animation

No, it's about finalizing of already received user input that should be finished. The animation's inputs are dynamic, so it's about finishing, not repeating

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt (hunk 1 above)
Comment (MatkovIvan) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:151]: I'd like to emphasize that it's not density. Also, it's not a change of this PR

Comment (elijah-semyonov) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:151]: It's a minuscule change, so I can't imagine a separate PR for it. I didn't get the emphasise of it, thus asked about the intention (may be there was a value different from 1f, that later was changed to 1f during iterating and someone forgot to delete it).

Comment (MatkovIvan) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt:151]: > may be there was a value different from 1f, that later was changed to 1f during iterating and someone forgot to delete it

It's true - it was not `1f` before, but I decided to keep it explicit here
