### PR TITLE
DatePicker. Fix today circle

### LINKED ISSUE #3591: Today's date is not highlighted with a circle in the material3 datePicker on iOS.
**Describe the bug**
Today should be in the circle, like on the Android

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0

**To Reproduce**
Create DatePicker element and everything will be clear.

**Expected behavior**
Today should be in a circle, like on Android

**Screenshots**
Screenshot 2023-08-30 at 16 35 10
Screenshot 2023-08-30 at 16 35 22

On android everything is fine on iOS - 30.08 is not in the circle.

### PR DESCRIPTION
**Pull request by alexzhirkevich**
## Proposed Changes

1. Fix one more bug from https://github.com/JetBrains/compose-multiplatform-core/pull/717 🥲.
Today time millis should be at the midnight.
Added the last test from Android that checks the equality of legacy and new models. Forgot to do it in the first PR.
 Prostite brakodela 🙏

2. Use narrow weekdays format instead of short (as in non-legacy model on Android). 
It should be more consistent with Android 26+ (see screenshots from fixed issue).
Also removed hardcoded weekdays names as all platforms have localized ones.

3. Replace input format building with existing function from common (missed that it already exists). It should be more stable for unusual locales.

4. `atStartOfDay` can produce [non-midnight time](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/at-start-of-day-in.html). Some calendar model methods require midnight and some start of day. Aligned all methods with the newer android implementation

## Testing

Test: `EqualityOfCalendarModelsTest`. This should protect from other bugs i believe

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3591

### CODE REVIEW

**Comment by m-sasha** [comment]
@alexzhirkevich I started investigating before I noticed your PR.

> Today time millis should be at the start of day.

Indeed, this seems to be the problem.

File: compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt [hunk 1]
```diff
@@ -30,7 +30,11 @@ import kotlinx.datetime.toLocalDateTime
 internal class KotlinxDatetimeCalendarModel : CalendarModel {
 
     override val today: CalendarDate
-        get() = Clock.System.now().toCalendarDate(systemTZ)
+        get() = Clock.System.now()
+            .toLocalDateTime(systemTZ)
+            .date
+            .atStartOfDayIn(TimeZone.UTC)
+            .toCalendarDate(TimeZone.UTC)
```
Comment (m-sasha) [inline compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Are you sure this is correct?

Maybe use this instead? It seems clearer and closer to Android's implementation:
```
    override val today: CalendarDate
        get() {
            val localDate = Clock.System.now().toLocalDateTime(systemTZ)
            return CalendarDate(
                year = localDate.year,
                month = localDate.monthNumber,
                dayOfMonth = localDate.dayOfMonth,
                utcTimeMillis = localDate.date
                    .atTime(hour = 0, minute = 0)
                    .toInstant(TimeZone.UTC)
                    .toEpochMilliseconds()
            )
        }
```
(just a suggestion; times are hard and it's hard to be sure of anything).

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: This indeed looks cleaner. I’ll check if it produces the same result as legacy model in different time zones and let you know

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Applied suggestion. Actually the result is the same, but this looks cleaner and probably has better performance as does not require double to-date conversion

File: compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt [hunk 2]
```diff
@@ -23,18 +23,26 @@ import kotlinx.datetime.LocalDate
...
-            .atStartOfDayIn(TimeZone.UTC)
-            .toCalendarDate(TimeZone.UTC)
+        get() {
+            val localDate = Clock.System.now().toLocalDateTime(systemTZ)
+            return CalendarDate(
+                year = localDate.year,
+                month = localDate.monthNumber,
+                dayOfMonth = localDate.dayOfMonth,
+                utcTimeMillis = localDate.date
+                    .atStartOfDayIn(TimeZone.UTC)
```
Comment (m-sasha) [inline compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/at-start-of-day-in.html says `atStartOfDay` isn't necessarily at midnight, and we do want midnight here because of how `isToday` is computed: 
```
val dateInMillis = month.startUtcTimeMillis + (dayNumber * MillisecondsIn24Hours)
val isToday = dateInMillis == today.utcTimeMillis
```
that's why I suggested to use `atTime(0,0)`.

Comment (m-sasha) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Or maybe both will be wrong, that is neither will match `dateInMillis`? I'm not sure. The way `isToday` is computed looks bad to me.

But Android uses 
```
utcTimeMillis = systemLocalDate.atTime(LocalTime.MIDNIGHT)
                    .atZone(utcTimeZoneId).toInstant().toEpochMilli()
```
so maybe it's better to stick with that, unless you're sure `atStartOfDayIn` is correct.

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Hmm, this is what CalendarModel interface comments (from canonical date method) says about it:
https://github.com/JetBrains/compose-multiplatform-core/blob/8f57b8cb30b6b07b995160cc946dfe78a53d1308/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/CalendarModel.kt#L94-L95

So it does not exactly say it needs to be 00:00, but start of day 🤔

Maybe `today` method should behave differently

--- 

Newer android calendar model takes it at midnight, lets do the same 
(but canonical date it takes at start of day 🥲🔫)

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt:42]: >so maybe it's better to stick with that

I agree. I compare every method that uses start of day / midnight in android implementation and refactor it in kotlinx to be the same.

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt:42]: Looks like the only place where `atStartOfDay` is used on Android is canonical date 🤷‍♂️. All other places use midnight

Comment (alexzhirkevich) [reply compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Aligned all methods with the Android implementation

File: compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt [hunk 3]
```diff
@@ -31,6 +32,8 @@ import kotlinx.datetime.toLocalDateTime
 
 internal class KotlinxDatetimeCalendarModel : CalendarModel {
 
+    private val midnight = LocalTime(0,0)
```
Comment (m-sasha) [inline compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/KotlinxDatetimeCalendarModel.kt]: Maybe put it outside the class, to avoid using memory for it:
```
private val Midnight = LocalTime(0,0)
```

**Review by m-sasha — APPROVED** [review]

**Comment by m-sasha** [comment]
@alexzhirkevich Would you like me to merge this?

**Comment by alexzhirkevich** [comment]
> @alexzhirkevich Would you like me to merge this?

Yep if everything looks good to you
