### PR TITLE
Enforce proper closing of ComposeScene in tests

### LINKED ISSUE #2713: Fix `GraphicsLayerTest.rotationY` test
**Describe the bug**

It seems `needRedraw` sometimes called from non-UI thread. We should either remove the thread requirement in skiko, or move this call to UI thread.

https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_Publish_2_AllGitHubRelease/4074124?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.4-alpha01

### PR DESCRIPTION
**Pull request by m-sasha**
Currently, when using `runApplicationTest` with `launchApplication`, any `Windows` and `Dialogs` opened inside would leak the window, along with its `ComposeScene`, possibly causing failures in other tests, such as this: https://github.com/JetBrains/compose-multiplatform/issues/2713

## Proposed Changes

  - Replace `launchApplication` with `launchTestApplication` in all our tests.
  - Overload `launchApplication` in `WindowTestScope`, making it impossible to use `launchApplication` from `runApplicationTest`.
  - Remove redundant `exitApplication` and `isOpen = false` code from all the tests.

## Testing

Test: Count and print `ComposeScene` instances by storing them in a list in the constructor and removing in `close()`. Then run the tests with `./scripts/testDesktop`.

Before this fix, we would end up with 46 unclosed instances, and the screen would be full of windows. Afterwards, the tests finish with 0 unclosed instances and the windows disappear after each test is completed.

ComposeScene:
```
private val composeScenes = mutableSetOf<ComposeScene>()
private val sync = createSynchronizedObject()

fun addComposeScene(scene: ComposeScene){
    synchronized(sync){
        println("ComposeScenes before adding: ${composeScenes.size}")
        composeScenes.add(scene)
    }
}

fun removeComposeScene(scene: ComposeScene){
    synchronized(sync){
        composeScenes.remove(scene)
        println("ComposeScenes after removal: ${composeScenes.size}")
    }
}

class ComposeScene(...){
    init {
        addComposeScene(this)
    }

    fun close() {
        removeComposeScene(this)
        ...
    }
}
```

## Issues Fixed

Possibly fixes https://github.com/JetBrains/compose-multiplatform/issues/2713

### CODE REVIEW

File: compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt [hunk 1]
```diff
@@ -111,19 +114,20 @@ internal class WindowTestScope(
...
+    ) = realLaunchApplication {
         if (isOpen) {
             content()
         }
     }
 
-    // TODO(demin) remove when we migrate from launchApplication to launchTestApplication (see TODO above)
-    fun exitApplication() {
-        isOpen = false
+    // Overload `launchApplication` to prohibit calling it from tests
```
Comment (igordmn) [inline compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt:125]: Good idea!

**Review by igordmn — APPROVED** [review]

File: compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt [hunk 2]
```diff
@@ -63,8 +63,11 @@ internal fun runApplicationTest(
             val exceptionHandler = TestExceptionHandler()
             withExceptionHandler(exceptionHandler) {
                 val scope = WindowTestScope(this, useDelay, hasAnimations, exceptionHandler)
-                scope.body()
-                scope.exitTestApplication()
+                try{
```
Comment (MatkovIvan) [inline compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt]:
```suggestion
                try {
```

File: compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt [hunk 3]
```diff
@@ -111,19 +114,20 @@ internal class WindowTestScope(
...
 
-    // TODO(demin) remove when we migrate from launchApplication to launchTestApplication (see TODO above)
-    fun exitApplication() {
-        isOpen = false
+    // Overload `launchApplication` to prohibit calling it from tests
+    @Suppress("unused")
+    fun launchApplication(
+        @Suppress("UNUSED_PARAMETER") content: @Composable ApplicationScope.() -> Unit
+    ): Nothing {
+        error("Do not use `launchApplication` from tests; use `launchTestApplication` instead")
```
Comment (MatkovIvan) [inline compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt:133]: Do we have some annotation to inform about it before run?

Comment (igordmn) [reply compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt:133]: We can use Deprecated(Error)

Comment (m-sasha) [reply compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/TestUtils.kt:133]: Good idea, I've added
```
    @Deprecated(
        "Do not use `launchApplication` from tests; use `launchTestApplication` instead",
        level = DeprecationLevel.ERROR
    )
```
