### PR TITLE
Return `null` from ComposeAccessible.getAccessibleContext when the node has been removed

### LINKED ISSUE #3728: LayoutNode should be attached to an owner
**Describe the bug**

I have a column with a list created from a for loop. 

Each item in the list is wrapped with a call to `key`. This follows the example in the official docs for `key` [here](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#key(kotlin.Array,kotlin.Function0))

Each item is a button that allows removing its own item from the list. 

When using this, whether it works correctly or not depends on the speed of how fast you remove items. If you remove them slowly, it will work perfectly as expected. But, if you hover your mouse over the first button and rapidly click to remove them, you will get the following error. The exception seems to be handled internally and is not raised to the user. However, it is printed to the console, indicating to the developer that something is wrong.

```text
java.lang.IllegalStateException: LayoutNode should be attached to an owner
	at androidx.compose.ui.node.LayoutNodeKt.requireOwner(LayoutNode.kt:1448)
	at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui(LayoutNode.kt:421)
	at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:252)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:254)
	at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui(SemanticsNode.kt:236)
	at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui$default(SemanticsNode.kt:229)
	at androidx.compose.ui.semantics.SemanticsNode.findOneLayerOfMergingSemanticsNodes(SemanticsNode.kt:343)
	at androidx.compose.ui.semantics.SemanticsNode.findOneLayerOfMergingSemanticsNodes$default(SemanticsNode.kt:340)
	at androidx.compose.ui.semantics.SemanticsNode.getChildren(SemanticsNode.kt:307)
	at androidx.compose.ui.semantics.SemanticsNode.getReplacedChildren$ui(SemanticsNode.kt:281)
	at androidx.compose.ui.platform.ComposeAccessible$ComposeAccessibleComponent.getAccessibleChildrenCount(ComposeAccessible.kt:299)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(CAccessibility.java:486)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(CAccessibility.java:470)
	at java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(LWCToolkit.java:698)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Affected platforms**

- Desktop

I have only tested Desktop. This may happen on other platforms as well, but I have not checked.

**Versions**
- Kotlin version*: 1.9.20-Beta2
- Compose Multiplatform version*:  Gradle plugin version 1.5.10-beta01, compiler version 1.5.2.1-Beta2
- OS version(s)* (required for Desktop and iOS issues): MacOs 13.5.2
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): Temurin 18

**To Reproduce**

1. Copy the code below, in a project with the versions above
2. Run the application
3. Hover your mouse of "Remove 1"
4. Slowly click the button once per second until all buttons are gone
5. Observe that there is no error
6. Restart the app
7. Repeat steps 3 and 4, but this time click as rapidly as you can
8. Observe the error output with the IllegalStateException that was thrown

```kotlin
import androidx.compose.foundation.layout.Column
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.key
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() {
    val list = mutableStateListOf(*(1..10).toList().toTypedArray())
    application {
        Window(visible = true, onCloseRequest = {
            exitApplication()
        }) {
            Column {
                for (i in list) {
                    key(i) {
                        Button(
                            onClick = { list.remove(i) }
                        ) {
                            Text("Remove $i")
                        }
                    }
                }
            }
        }
    }
}

```

**Expected behavior**

There should not be an error.

### PR DESCRIPTION
**Pull request by m-sasha**
The long story of this PR is this:

I reproduced the printed exception in https://github.com/JetBrains/compose-multiplatform/issues/3728 and noticed that we don't report to the accessibility system anywhere when a node has been removed. So I thought it wasn't surprising that it would continue calling functions on it, which would then throw that exception.

So I set out to report node addition/removal by correctly firing `AccessibleContext.ACCESSIBLE_CHILD_PROPERTY` property change events. When that didn't do anything, I realized that `ComposeAccessibleComponent` doesn't have the child/parent hierarchy set up correctly, and thought that perhaps this is confusing the system.

Specifically `rootAccessible` in `AccessibilityControllerImpl` (which is only the root for a single `SemanticsOwner`, so it's not really the root) doesn't report having a parent, even though `ComposeSceneAccessibleContext` returns it from `getAccessibleChild`. So I fixed that. But unfortunately that didn't help either.

Then I decided to see what exactly the system does when it receives an `ACCESSIBLE_CHILD_PROPERTY` property change event. Turns out that `AXChangeNotifier` (the accessible listener on macOS) doesn't even listen to that event, and its (native) `ptr` is `null` altogether for some reason.

So then I just gave up and implemented this PR. It simply marks `ComposeAccessible`s as removed when they are removed, and their `getAccessibleContext` then returns `null`. In `CAccessibility.java`, all the getter functions check the return value of `getAccessibleContext` and return `null` if it returns `null`.

If we want to properly report `ACCESSIBLE_CHILD_PROPERTY` events and have the parents set up correctly, I can submit a separate PR, or just keep it stashed for now.

## Proposed Changes

 When the semantics node of a `ComposeAccessible` is removed, mark it as removed, and have it return `null` from `getAccessibleContext`.

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3728

### CODE REVIEW

File: compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/ComposeAccessible.kt [hunk 1]
```diff
@@ -91,7 +91,15 @@ internal class ComposeAccessible(
 
     val composeAccessibleContext: ComposeAccessibleComponent by lazy { ComposeAccessibleComponent() }
 
-    override fun getAccessibleContext(): AccessibleContext {
+    var removed = false
```
Comment (Walingar) [inline compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/ComposeAccessible.kt:94]: Am I right that tree will be recreated after a while and ComposeAccessible will be collected? Otherwise it looks like a leak

**Review by Walingar — APPROVED** [review]
But anyway I also investigated this behavior when working on the issue with non-working accessibility in popups. I thought that the issue is that we are not notifying system about tree changes. But system doesn't even listen for the events.
So, for me this solution works for now, but I am afraid about possible leak

File: compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/ComposeAccessible.kt (hunk 1 above)
Comment (m-sasha) [reply compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/ComposeAccessible.kt:94]: Not sure I understand what you mean. The node is marked as `removed=false` when it's no longer in the tree. I'm not storing it anywhere it wasn't before.

`sun.lwawt.macosx.CAccessible` will probably keep storing a reference to it, but only until some other node becomes "active" (it only stores one `Accessible`).

Comment (Walingar) [reply compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/ComposeAccessible.kt:94]: Yes, I am talking about `sun.lwawt.macosx.CAccessible`, so I hope that ComposeAccessible won't be stored there forever
