### PR TITLE
Take into account `enabled` in `scrollable` for mouse input

### LINKED ISSUE #3816: Disabling user scroll doesn't work for LazyRow with touchpad
**Describe the bug**
Creating a lazy row with `userScrollEnabled` set to `false` doesn't prevent the user from being able to scroll the list with the touchpad.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)*: MacOS Ventura 
- OS architecture: arm64
- JDK (for desktop issues): Amazon Corretto 17.0.8

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create lazy row like this:
```
val scrollState = rememberLazyListState(1)
LazyRow(
    modifier = Modifier,
    state = scrollState,
    userScrollEnabled = false
) {
    ...
}
```
2. Try to scroll the lazy row with two fingers using touchpad
3. See the scroll

**Expected behavior**
No scrolling on the part of the user should be available.

**Screenshots**
The lazy row is used as a basis for a calendar widget to enable animated shifts between months. These details of implementation must be hidden from the user, however. The idea was to enable scrolling only with arrow buttons.
https://github.com/JetBrains/compose-multiplatform/assets/90451272/1140b9d2-abe8-4123-abc6-6ee25a2901bd

**Additional context**
I can still override user scroll events by adding this extension to the modifier:
```
fun Modifier.disableScroll() = this
    .pointerInput(Unit) {
        awaitEachGesture {
            val event = awaitPointerEvent(pass = PointerEventPass.Initial)
            if (event.type == PointerEventType.Scroll) {
                event.changes.onEach(PointerInputChange::consume)
            }
        }
    }
```
However, my impression is that the userScrollEnabled parameter is meant exactly for this, or am I wrong?

### PR DESCRIPTION
**Pull request by igordmn**
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3816

## Testing
1. The new test
2. Manual testing of `Modifier.verticalScroll(enabled = false`

### CODE REVIEW

File: compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt [hunk 1]
```diff
@@ -75,12 +79,22 @@ internal class MouseWheelScrollableElement(
...
+        if (_enabled) {
+            mouseWheelInput()
+        }
     })
 
+    var enabled
+        get() = _enabled
+        set(value) {
+            _enabled = value
+            pointerInputNode.resetPointerInputHandler()
```
Comment (MatkovIvan) [inline compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt]: Maybe it's better to filter it on events instead of relying on another state?

Comment (igordmn) [reply compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/MouseWheelScrollable.kt]: If we have running animations, we should cancel them, restarting the pointerInput coroutine.

This code is the same as in Draggable.

**Review by MatkovIvan — APPROVED** [review]
