### PR TITLE
fix pointerHoverIcon: update icon when it's changed conditionally

### LINKED ISSUE #2091: pointerHoverIcon changes only after pointer event
```kotlin
fun main() {
    var isCtrlPressed: Boolean by mutableStateOf(false)

    singleWindowApplication(
        onPreviewKeyEvent = {
            isCtrlPressed = it.isCtrlPressed
            false
        }
    ) {
        Box(modifier = Modifier
            .size(100.dp)
            .background(Color.Blue)
            .pointerHoverIcon(if (isCtrlPressed) PointerIconDefaults.Hand else PointerIconDefaults.Default)
        ) 
    }
}
```
If we hover the box and press Ctrl, the cursor icon won't change until we move the cursor. 
From the name of a function `pointerHoverIcon` it's not obvious that it's necessary that pointer should move in order to get updated.

Also SkiaBasedOwner calls commitCursor() only in processPointerInput(). Can we call commitCursor() in PointerIconService implementation?

Like this:
```
object : PointerIconService {
            override var current: PointerIcon
                get() = getPointerIcon(component)
                set(value) {
                    setPointerIcon(component, value)
                    commitPointerIcon(component) // add this call?
                }
        }
```

I guess it was not added here for some reason.

### PR DESCRIPTION
**Pull request by eymar**
fixes https://github.com/JetBrains/compose-jb/issues/2091

### CODE REVIEW

File: compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerIcon.kt [hunk 1]
```diff
@@ -73,21 +72,29 @@ fun Modifier.pointerHoverIcon(icon: PointerIcon, overrideDescendants: Boolean =
...
             Modifier
         } else {
-            this.pointerInput(icon, overrideDescendants) {
+            val rememberIcon = rememberUpdatedState(icon)
+            val rememberOverrideDescendants = rememberUpdatedState(overrideDescendants)
+
+            // Create and chain a new instance of a dumbModifier for every new icon.
+            // This forces the LayoutNode to requestRelayout, leading to a synthetic event being dispatched
+            // and then handled here in pointerInput below, and then applying the icon to the pointerIconService.
+            val dumbModifier = remember(icon) { object : Modifier.Element {} }
```
Comment (igordmn) [inline compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerIcon.kt]: This uses implementation details of the how relayout happens. In the future there can be an optimisation to not perform relayout on new empty modifiers.

What if we tell explicitly, that we need a new synthetic event?
```
SideEffect {
   pointerIconService.refresh()
}

override val pointerIconService = object : PointerIconService {
    override var current: PointerIcon = PointerIconDefaults.Default

    fun refresh() = pointerPositionUpdater.onLayout() // better to rename onLayout to `needUpdate`, because now we call it not only on layout
}
```

Also, if it is not complicated, better to write a test to this behaviour.

Comment (eymar) [reply compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerIcon.kt]: done.
I decided to use DisposableEffect(key = icon) instead of a SideEffect, to avoid requesting the update for every recomposition. 


We also can add DisposableEffect conditionally: only when a component is hovered: if (isHovered) DisapobleEffect.

Comment (igordmn) [reply compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/input/pointer/PointerIcon.kt]: > We also can add DisposableEffect conditionally: only when a component is hovered: if (isHovered) DisapobleEffect.

Great idea ). Let's do this way

**Review by igordmn — APPROVED** [review]
