### PR TITLE
Correctly merge `ExposedDropdownMenu` from Material 3 1.3

### LINKED ISSUE #4782: TextField cannot input in ExposedDropdownMenuBox, when ExposedDropdownMenu is expanded
### Discussed in https://github.com/JetBrains/compose-multiplatform/discussions/4693

<div type='discussions-op-text'>

<sup>Originally posted by **JasonMing** April 24, 2024</sup>
> - Kotlin version*: 1.9.23
> - Compose Multiplatform version*: 1.6.5

I'm trying to implement a filterable drop down menu in **Compose Web** by using **Material3**'s `ExposedDropdownMenuBox`.
```kotlin
var expand by remember { mutableStateOf(false) }
var text by remember { mutableStateOf("") }
ExposedDropdownMenuBox(
    expanded = expand,
    onExpandedChange = { expand = !expand },
) {
    OutlinedTextField(
        value = text,
        label = { Text("Options") },
        onValueChange = {
            text = it
        },
        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expand) },
        modifier = Modifier.menuAnchor(),
    )

    ExposedDropdownMenu(
        expanded = expand,
        onDismissRequest = { expand = false },
    ) {
        listOf("foo", "bar", "baz")
            .filter { it.contains(text) }
            .forEach {
                DropdownMenuItem(
                    text = { Text(it) },
                    onClick = {
                        text = it
                        expand = false
                    }
                )
            }
    }
}
```
image

After click the TextField, menu will auto expand.
The focus is still on the TextField, it should be able to input, but actually NOT.
If I collapse the menu, the TextField will be able to input again.
</div>

### LINKED ISSUE #5033: Keyboard not opening in iOS When using ExposedDropdownMenu
**Describe the bug**
Keyboard not opening in iOS When using ExposedDropdownMenu

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
1. Run this code snippet:
    ```kotlin
    Box(
      modifier = Modifier.fillMaxSize(),
      contentAlignment = Alignment.Center
    ) {
        val options = remember { (0..5).map { "Test $it" } }
        var text by remember { mutableStateOf("") }
        var isExpanded by remember { mutableStateOf(false) }

        ExposedDropdownMenuBox(
            expanded = isExpanded,
            onExpandedChange = { isExpanded = it }
        ) {
            OutlinedTextField(
                value = text,
                onValueChange = { text = it },
                modifier = Modifier.fillMaxWidth().menuAnchor(),
                trailingIcon = {
                    IconButton(onClick = { isExpanded = !isExpanded }) {
                        ExposedDropdownMenuDefaults.TrailingIcon(isExpanded)
                    }
                }
            )

            ExposedDropdownMenu(
                expanded = isExpanded,
                onDismissRequest = { isExpanded = false },
                modifier = Modifier.fillMaxWidth()
            ) {
                options.forEach { item ->
                    DropdownMenuItem(
                        onClick = { text = item; isExpanded = false },
                        modifier = Modifier.fillMaxWidth(),
                        text = { Text(text = item) },
                    )
                }
            }
        }
    }
    ```
2. Click on The TextField
4. Keyboard wont open

**Expected behavior**
Keyboard should be opening

**Recording**

https://github.com/JetBrains/compose-multiplatform/assets/64367926/2047e8ba-5955-4049-bbbf-8939a4508d7a

### PR DESCRIPTION
**Pull request by MatkovIvan**
Missing changes during Material 3 1.3 merge

Fixes https://github.com/JetBrains/compose-multiplatform/issues/4782
Fixes https://github.com/JetBrains/compose-multiplatform/issues/5033

### Fixes - Multiple Platforms

- Fix focus for editable `TextField` inside `ExposedDropdownMenuBox`

### CODE REVIEW

File: compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/components/material3/DropdownMenu3Example.kt [hunk 1]
```diff
@@ -107,7 +108,7 @@ internal fun TextFieldWithExposedDropdown() {
         onExpandedChange = { expanded = !expanded },
     ) {
         TextField(
-            modifier = Modifier.menuAnchor(),
+            modifier = Modifier.menuAnchor(MenuAnchorType.PrimaryNotEditable),
```
Comment (m-sasha) [inline compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/components/material3/DropdownMenu3Example.kt:111]: Maybe add examples of the other two MenuAnchorTypes.

**Review by m-sasha — APPROVED** [review]

File: compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/components/material3/DropdownMenu3Example.kt (hunk 1 above)
Comment (MatkovIvan) [reply compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/components/material3/DropdownMenu3Example.kt:111]: Yeah, we have a lot of new elements that should be tested/covered. Let's do it separately from the merge (and fixing bad merge)
